# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class LoginPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, token=None, name=None):  # noqa: E501
        """LoginPost201Response - a model defined in OpenAPI

        :param message: The message of this LoginPost201Response.  # noqa: E501
        :type message: str
        :param token: The token of this LoginPost201Response.  # noqa: E501
        :type token: str
        :param name: The name of this LoginPost201Response.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'message': str,
            'token': str,
            'name': str
        }

        self.attribute_map = {
            'message': 'message',
            'token': 'token',
            'name': 'name'
        }

        self._message = message
        self._token = token
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'LoginPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _login_post_201_response of this LoginPost201Response.  # noqa: E501
        :rtype: LoginPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this LoginPost201Response.

        The success message.  # noqa: E501

        :return: The message of this LoginPost201Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this LoginPost201Response.

        The success message.  # noqa: E501

        :param message: The message of this LoginPost201Response.
        :type message: str
        """

        self._message = message

    @property
    def token(self):
        """Gets the token of this LoginPost201Response.

        The access token.  # noqa: E501

        :return: The token of this LoginPost201Response.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this LoginPost201Response.

        The access token.  # noqa: E501

        :param token: The token of this LoginPost201Response.
        :type token: str
        """

        self._token = token

    @property
    def name(self):
        """Gets the name of this LoginPost201Response.

        The user's name.  # noqa: E501

        :return: The name of this LoginPost201Response.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LoginPost201Response.

        The user's name.  # noqa: E501

        :param name: The name of this LoginPost201Response.
        :type name: str
        """

        self._name = name
