# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RegisterPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, token=None):  # noqa: E501
        """RegisterPost201Response - a model defined in OpenAPI

        :param message: The message of this RegisterPost201Response.  # noqa: E501
        :type message: str
        :param token: The token of this RegisterPost201Response.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'message': str,
            'token': str
        }

        self.attribute_map = {
            'message': 'message',
            'token': 'token'
        }

        self._message = message
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _register_post_201_response of this RegisterPost201Response.  # noqa: E501
        :rtype: RegisterPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this RegisterPost201Response.

        Success message.  # noqa: E501

        :return: The message of this RegisterPost201Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this RegisterPost201Response.

        Success message.  # noqa: E501

        :param message: The message of this RegisterPost201Response.
        :type message: str
        """

        self._message = message

    @property
    def token(self):
        """Gets the token of this RegisterPost201Response.

        Access token for the user.  # noqa: E501

        :return: The token of this RegisterPost201Response.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this RegisterPost201Response.

        Access token for the user.  # noqa: E501

        :param token: The token of this RegisterPost201Response.
        :type token: str
        """

        self._token = token
