# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RegisterPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name=None, last_name=None, email=None, password=None, confirm_password=None):  # noqa: E501
        """RegisterPostRequest - a model defined in OpenAPI

        :param first_name: The first_name of this RegisterPostRequest.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this RegisterPostRequest.  # noqa: E501
        :type last_name: str
        :param email: The email of this RegisterPostRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterPostRequest.  # noqa: E501
        :type password: str
        :param confirm_password: The confirm_password of this RegisterPostRequest.  # noqa: E501
        :type confirm_password: str
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'email': str,
            'password': str,
            'confirm_password': str
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'password': 'password',
            'confirm_password': 'confirmPassword'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._password = password
        self._confirm_password = confirm_password

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _register_post_request of this RegisterPostRequest.  # noqa: E501
        :rtype: RegisterPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self):
        """Gets the first_name of this RegisterPostRequest.

        User's first name.  # noqa: E501

        :return: The first_name of this RegisterPostRequest.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this RegisterPostRequest.

        User's first name.  # noqa: E501

        :param first_name: The first_name of this RegisterPostRequest.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this RegisterPostRequest.

        User's last name.  # noqa: E501

        :return: The last_name of this RegisterPostRequest.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this RegisterPostRequest.

        User's last name.  # noqa: E501

        :param last_name: The last_name of this RegisterPostRequest.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this RegisterPostRequest.

        User's email address.  # noqa: E501

        :return: The email of this RegisterPostRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this RegisterPostRequest.

        User's email address.  # noqa: E501

        :param email: The email of this RegisterPostRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this RegisterPostRequest.

        User's password.  # noqa: E501

        :return: The password of this RegisterPostRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RegisterPostRequest.

        User's password.  # noqa: E501

        :param password: The password of this RegisterPostRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def confirm_password(self):
        """Gets the confirm_password of this RegisterPostRequest.

        Confirmation of user's password.  # noqa: E501

        :return: The confirm_password of this RegisterPostRequest.
        :rtype: str
        """
        return self._confirm_password

    @confirm_password.setter
    def confirm_password(self, confirm_password):
        """Sets the confirm_password of this RegisterPostRequest.

        Confirmation of user's password.  # noqa: E501

        :param confirm_password: The confirm_password of this RegisterPostRequest.
        :type confirm_password: str
        """
        if confirm_password is None:
            raise ValueError("Invalid value for `confirm_password`, must not be `None`")  # noqa: E501

        self._confirm_password = confirm_password
