# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdateProfilePut404Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """UpdateProfilePut404Response - a model defined in OpenAPI

        :param message: The message of this UpdateProfilePut404Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateProfilePut404Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _update_profile_put_404_response of this UpdateProfilePut404Response.  # noqa: E501
        :rtype: UpdateProfilePut404Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this UpdateProfilePut404Response.

        An error message explaining the reason for the error.  # noqa: E501

        :return: The message of this UpdateProfilePut404Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this UpdateProfilePut404Response.

        An error message explaining the reason for the error.  # noqa: E501

        :param message: The message of this UpdateProfilePut404Response.
        :type message: str
        """

        self._message = message
