# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdateProfilePut401Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, msg=None):  # noqa: E501
        """UpdateProfilePut401Response - a model defined in OpenAPI

        :param msg: The msg of this UpdateProfilePut401Response.  # noqa: E501
        :type msg: str
        """
        self.openapi_types = {
            'msg': str
        }

        self.attribute_map = {
            'msg': 'msg'
        }

        self._msg = msg

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateProfilePut401Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _update_profile_put_401_response of this UpdateProfilePut401Response.  # noqa: E501
        :rtype: UpdateProfilePut401Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg(self):
        """Gets the msg of this UpdateProfilePut401Response.

        An error message explaining the reason for the error.  # noqa: E501

        :return: The msg of this UpdateProfilePut401Response.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this UpdateProfilePut401Response.

        An error message explaining the reason for the error.  # noqa: E501

        :param msg: The msg of this UpdateProfilePut401Response.
        :type msg: str
        """

        self._msg = msg
